version: '3.9'

services:
  app:
    container_name: tic-tac-toe-app
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '3000:3000'
    volumes:
      - .:/app
      - /app/node_modules
    command: npm run dev
